### PR TITLE
docs: add one-click-deploy link

### PR DESCRIPTION
**Pull request by jbgh**
Adds one-click-deploy link with Dome to the readme

@garyli27 here's the PR as we discussed

### CODE REVIEW

**Comment by ziqiangai** [comment]
Wow,  It looks good.
But can we add a badge, like this:
dome Badge
https://img.shields.io/badge/dome-devenv-blue

Or do you have any suggestions?

**Comment by jbgh** [comment]
Glad you like it! My suggestion is that we add the badge in addition to the quick start text. I've gone ahead and added the badge to the top of the readme. Great idea.

**Comment by paylm** [comment]
Are you maintaining this project in the long term? @jbgh 
After adding the entrance, some users asked about the deployment of Apitable on the trydome platform.

**Comment by jbgh** [comment]
Yes, we will be maintaining this long term, along with a very solid team. APITable is deployed through the Dome platform into our production environments which are maintained by our DevOps team. All a user needs to do is one-click deploy, and the platform will do the rest and the APITable package will run as expected in a reliable scalable environment.

**Review by paylm — APPROVED** [review]

**Pull request merged**
